### ISSUE TITLE
Make STJ Conditional based on TFM

### ISSUE THREAD

**Issue by thompson-tomo** [PicoHex/Zaabee.Serialization#2]
**Is your feature request related to a problem? Please describe.**
I want to minimise dependencies in my project by utilising framework dependencies wherever possible

**Describe the solution you'd like**
I want the package to not have an explicit dependency on System.Text.Json as it can be provided by the framework when targeting net 6. 

**Describe alternatives you've considered**
Accept the additional dependency

**Additional context**
n/a

**Comment by Mutuduxf** [comment]
Thank you. I have pushed the Zaabee.SystemTextJson 2024.1.8 package to Nuget and added a package reference condition to it.
