### ISSUE TITLE
Set repo url for nuget package

### ISSUE THREAD

**Issue by thompson-tomo** [PicoHex/Zaabee.Serialization#3]
### Summary
I wish for the nuget packages to have the repository url set correctly

### Details

By providing the repo url it will make it easier to contribute and can be used by source-link.

**Comment by Mutuduxf** [comment]
Hi @thompson-tomo , in this repo, it provided 19 packages (18 for difference serializers and one for abstractions) and all packages have set the repo url.

**Comment by thompson-tomo** [comment]
Hi @Mutuduxf i just checked and not one has the repository url set. Note repository url is different to project url which is set.

**Comment by Mutuduxf** [comment]
> Hi @Mutuduxf i just checked and not one has the repository url set. Note repository url is different to project url which is set.

OK, i will check it after the rest.

**Comment by Mutuduxf** [comment]
> Hi @Mutuduxf i just checked and not one has the repository url set. Note repository url is different to project url which is set.

Hi @thompson-tomo , I have added repository information (RepositoryUrl and RepositoryType) to the package. You can upgrade to 2024.1.9, and feel free to contact me if you have any questions.

**Comment by thompson-tomo** [comment]
Looks good to me.

**Comment by Mutuduxf** [comment]
It looks good to me.

Hi @thompson-tomo, I have added a source link to it, which may give you more help. Of course,  feel free to contact me if you have any questions.
